// <auto-generated />
using System;
using CCTime.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CCTime.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227203247_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CCTime.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsArchived = false,
                            Name = "-",
                            OrderIndex = 0
                        });
                });

            modelBuilder.Entity("CCTime.Domain.Entities.Reserve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ClientConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("client_confirmed");

                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000001"))
                        .HasColumnName("client_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<bool>("SpecialistConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("specialist_confirmed");

                    b.Property<Guid>("SpecialistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000001"))
                        .HasColumnName("specialist_id");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_slot_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("Date", "TimeSlotId", "RoomId")
                        .IsUnique();

                    b.ToTable("reserves", (string)null);
                });

            modelBuilder.Entity("CCTime.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0000-0000-000000000001"),
                            Name = "ЛОГО",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0000-0000-000000000002"),
                            Name = "НЕЙРО",
                            OrderIndex = 2
                        });
                });

            modelBuilder.Entity("CCTime.Domain.Entities.Specialist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.HasKey("Id");

                    b.ToTable("specialists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsArchived = false,
                            Name = "-",
                            OrderIndex = 0
                        });
                });

            modelBuilder.Entity("CCTime.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("time_slots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000001"),
                            Name = "8.30-9.15",
                            OrderIndex = 1,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000002"),
                            Name = "9.15-10.00",
                            OrderIndex = 2,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000003"),
                            Name = "10.00-10.45",
                            OrderIndex = 3,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000004"),
                            Name = "перерыв 15 мин",
                            OrderIndex = 4,
                            Type = "break"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000005"),
                            Name = "11.00-11.45",
                            OrderIndex = 5,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000006"),
                            Name = "11.45-12.30",
                            OrderIndex = 6,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000007"),
                            Name = "12.30-13.15",
                            OrderIndex = 7,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000008"),
                            Name = "обед",
                            OrderIndex = 8,
                            Type = "break"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000009"),
                            Name = "13.30-14.15",
                            OrderIndex = 9,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000010"),
                            Name = "14.15-15.00",
                            OrderIndex = 10,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000011"),
                            Name = "15.00-15.45",
                            OrderIndex = 11,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000012"),
                            Name = "перерыв 15 мин",
                            OrderIndex = 12,
                            Type = "break"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000013"),
                            Name = "16.00-16.45",
                            OrderIndex = 13,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000014"),
                            Name = "16.45-17.30",
                            OrderIndex = 14,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000015"),
                            Name = "17.30-18.15",
                            OrderIndex = 15,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000016"),
                            Name = "перерыв 15 мин",
                            OrderIndex = 16,
                            Type = "break"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000017"),
                            Name = "18.30-19.15",
                            OrderIndex = 17,
                            Type = "work"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0000-0000-000000000018"),
                            Name = "19.15-20.00",
                            OrderIndex = 18,
                            Type = "work"
                        });
                });

            modelBuilder.Entity("CCTime.Domain.Entities.Reserve", b =>
                {
                    b.HasOne("CCTime.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCTime.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCTime.Domain.Entities.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCTime.Domain.Entities.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Room");

                    b.Navigation("Specialist");

                    b.Navigation("TimeSlot");
                });
#pragma warning restore 612, 618
        }
    }
}
